### ISSUE TITLE
Plugin should allow base url setting

### ISSUE THREAD

**Issue by emu-pl** [emilwojtaszek/fastlane-plugin-au_auto_close_upload#1]
Please check documentation inside auto-close - there is an additional parameter that allows to set base url - it's important for the links provided in response after upload:

Example usage:
`python tools/upload.py --base-url https://builds.appunite.com/`

It'd be great to have this ability in this fastlane plugin too.

**Comment by SzymonMrozek** [comment]
Same here ➕

**Comment by SzymonMrozek** [comment]
Totally useless plugin ...

**Comment by SzymonMrozek** [comment]
Also adding `json-output-file` would be great!

**Comment by emilwojtaszek** [comment]
gosh...

**Comment by emilwojtaszek** [comment]
@SzymonMrozek happy to see and review pull requests ;p

**Comment by SzymonMrozek** [comment]
gosh...

**Comment by emilwojtaszek** [comment]
fixed in 8084ef32f1dc8a71ee21d6e2beed7645ff85d9f7
